classdef LiprasDialog
    % Generates dialog boxes 
    properties (Constant)
        ScreenSize = get(0, 'ScreenSize');
        
    end
    
    methods (Static)
        function dlg = fittingDataSet()
        % Creates a dialog box with a Cancel button while waiting for fitting to complete.
        dPosition = LiprasDialog.centeredPosition([300 100]);
        dlg = dialog('Name', 'Fitting Dataset...', ...
                     'Position', dPosition);
        uicontrol(dlg, 'Style', 'text', ...
                  'String', 'Peak fitting in progress. Please wait...', ...
                  'FontName', 'default', ...
                  'FontSize', 10, ...
                  'Units', 'normalized', ...
                  'tag', 'text', ...
                  'Position', [0.1 0.5 0.8 0.3]);
        btnSize = [75 30];
        uicontrol(dlg, 'Style', 'pushbutton', ...
                 'Tag', 'btn', ...
                 'String', 'Cancel', ...
                 'FontName', 'default', ...
                 'FontSize', 10, ...
                 'Units', 'pixels', ...
                 'Position', [0.5*[dPosition(3)-btnSize(1), 0.7*dPosition(4)-btnSize(2)], btnSize], ...
                 'Callback', 'delete(gcf)');
        end
        
        function dlg = PolyNotUniqueWarning()
        % Issues a warning dialog when the number of background points is less than the background
        % polynomial order.
        msg = 'Polynomial is not unique; Polynomial order must be  > number of data points. Add more points to continue.';
        dlg = warndlg(msg, 'Warning');
        set(dlg, 'WindowStyle', 'modal', ...
            'WindowKeyPressFcn', 'delete(gcf)');
        end
        
        function pos = centeredPosition(dSize)
        % Returns a 1x2 numeric array POS of the position the dialog box of size DSIZE should be 
        %   located to be centered on the screen.
        pos = 0.5*[LiprasDialog.ScreenSize(3)-dSize(1), LiprasDialog.ScreenSize(4)-dSize(2)];
        pos = [pos dSize];
        end
    end
end